version: "2.3"

services:

  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 54:8600/udp

  downstream-service-1:
    image: wiremock/wiremock:2.32.0
    container_name: downstream-service-1
    ports:
      - 18000:8080
      - 18100:8443
    depends_on:
      consul:
        condition: service_started

  downstream-service-2:
    image: wiremock/wiremock:2.32.0
    container_name: downstream-service-2
    ports:
      - 18001:8080
      - 18101:8443
    depends_on:
      consul:
        condition: service_started
