server:
  port: 1234

spring:
  main:
    banner-mode: off
  # Config for Spring-Boot 3.x / Spring-Cloud 2022.x and newer
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 1000

# Config for Spring-Boot 2.7.x / Spring-Cloud 2021.x and older
feign:
  client:
    config:
      default:
        readTimeout: 1000
